-- ============================================================================
-- DEPRECATED: NormalizedTransactions Table
-- ============================================================================
-- 
-- This schema is OBSOLETE as of December 2025.
-- 
-- Raw transaction events are now stored in Azure Blob Storage as Parquet files
-- per the hybrid storage architecture (WO-61).
-- 
-- This schema is retained for reference to inform Parquet schema design.
-- See: docs/PARQUET-SCHEMA-DESIGN.md
--
-- Migration Path:
-- - Raw events → Azure Blob Storage (Parquet) - WO-63, WO-64, WO-65, WO-66
-- - Dynamic metrics → PostgreSQL dynamic_metrics table - WO-44
-- - Aggregate metrics → PostgreSQL aggregate_histograms table - WO-53
--
-- ============================================================================
-- Table: NormalizedTransactions (OBSOLETE - DO NOT USE)
-- Purpose: Reference schema for Parquet design
-- ============================================================================

-- This table structure informed the Parquet schema design:
-- 
-- Fields to include in Parquet:
--   - transaction_id (string)
--   - transaction_timestamp (timestamp)
--   - ingestion_timestamp (timestamp)
--   - processing_timestamp (timestamp)
--   - amount (decimal)
--   - currency (string, 3 chars)
--   - payment_method (string)
--   - payment_status (string)
--   - customer_id (string, nullable)
--   - customer_email (string, nullable)
--   - customer_country (string, 2 chars, nullable)
--   - merchant_id (string, nullable)
--   - merchant_name (string, nullable)
--   - merchant_category (string, nullable)
--   - transaction_type (string, nullable)
--   - channel (string, nullable)
--   - device_type (string, nullable)
--   - metadata (JSON object, stored as string in Parquet)
--   - created_at (timestamp)
--   - updated_at (timestamp)
--
-- See: src/function_app/storage/parquet_schema.py for implementation

-- DO NOT EXECUTE THIS SCRIPT
-- This file is for reference only
